#Luīze Karpika
print('nākamā rinda tukša\n')
print()
print('Visi vārdi vienā rindā')
print('Visi ',end='')
print('vārdi ',end='')
print('vienā ',end='')
print('rindā ',end='')
print('\nNo zvaigznītēm * veidots trijstūris')
print('  *')
print(' * *')
print('*****')